# Generated by Django 5.1.4 on 2025-01-03 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_options_task_priority_alter_task_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 2, 58, 15, 998701, tzinfo=datetime.timezone.utc), verbose_name='登録日'),
        ),
    ]
