# Generated by Django 5.1.4 on 2025-01-03 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_task_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 3, 3, 26, 932348, tzinfo=datetime.timezone.utc), verbose_name='登録日'),
        ),
    ]
