# Generated by Django 5.1.4 on 2025-02-23 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_task_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.CharField(default='0%', max_length=4, verbose_name='進捗'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 6, 15, 6, 717119, tzinfo=datetime.timezone.utc), verbose_name='登録日'),
        ),
    ]
