# Generated by Django 5.1.4 on 2025-03-26 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_task_progress_alter_task_notes_alter_task_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Markdown形式で記述できます', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 26, 16, 15, 20, 327078, tzinfo=datetime.timezone.utc), verbose_name='登録日'),
        ),
    ]
